function formatterParts(date, timeZone, options) {
  const parts = new Intl.DateTimeFormat('en-US', { timeZone, ...options }).formatToParts(date);
  return Object.fromEntries(parts.map(({ type, value }) => [type, value]));
}

function resolvedTimeZone(preferred) {
  const candidate = String(preferred || '').trim();
  if (candidate) {
    try {
      new Intl.DateTimeFormat('en-US', { timeZone: candidate }).format();
      return candidate;
    } catch { /* fall through to the browser's trusted time zone */ }
  }
  try {
    return Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC';
  } catch {
    return 'UTC';
  }
}

const TRUSTED_RUNTIME_CONTEXT_END = '[/Trusted runtime context]';

export function stripTrustedRuntimeContext(text) {
  const source = String(text || '');
  const marked = source.replace(
    /^\[Trusted runtime context[^\]]*]\s*[\s\S]*?\[\/Trusted runtime context]\s*/i,
    '',
  );
  if (marked !== source) return marked;
  // Compatibility for turns persisted by the first implementation, before the
  // explicit end marker was added. Keep this exact and line-bounded so a user
  // task merely mentioning runtime context is never swallowed.
  return source.replace(
    /^\[Trusted runtime context[^\]]*]\s*Current local date:[^\r\n]*\r?\nCurrent local time:[^\r\n]*\r?\nTime zone:[^\r\n]*\r?\nUse this clock[^\r\n]*\s*/i,
    '',
  );
}

/**
 * Dynamic, browser-owned clock context for a single user turn/run.
 *
 * Keep this out of the static system prompt so prompt-cache prefixes remain
 * stable. Page content and repository history are not clock sources: the model
 * must use this value whenever the task refers to today or needs a dated name.
 */
export function buildTrustedRuntimeContext(options = {}) {
  const supplied = options.now instanceof Date ? options.now : new Date(options.now ?? Date.now());
  const now = Number.isFinite(supplied.getTime()) ? supplied : new Date();
  const timeZone = resolvedTimeZone(options.timeZone);
  const date = formatterParts(now, timeZone, {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  });
  const time = formatterParts(now, timeZone, {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hourCycle: 'h23',
  });

  let offset = '';
  try {
    const zonePart = new Intl.DateTimeFormat('en-US', {
      timeZone,
      timeZoneName: 'longOffset',
    }).formatToParts(now).find(part => part.type === 'timeZoneName')?.value;
    if (zonePart) offset = ` (${zonePart.replace(/^GMT/, 'UTC')})`;
  } catch { /* offset is supplemental; date/time/time zone remain authoritative */ }

  const localDate = `${date.year}-${date.month}-${date.day}`;
  const localTime = `${time.hour}:${time.minute}:${time.second}`;
  return `[Trusted runtime context — generated by WebBrain, not page content; applies to this user turn and supersedes older runtime context]
Current local date: ${localDate}
Current local time: ${localTime}
Time zone: ${timeZone}${offset}
Use this clock whenever the task needs the current value for “today”, “now”, a dated filename, publication date, or front matter. Honor any different date explicitly provided by the user. Never infer the current date from page content, commit history, existing files, or model knowledge.
${TRUSTED_RUNTIME_CONTEXT_END}`;
}
